CREATE TABLE `ps_map_data_source_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `redkills` smallint unsigned NOT NULL default '0',
  `redassists` smallint unsigned NOT NULL default '0',
  `bluekills` smallint unsigned NOT NULL default '0',
  `blueassists` smallint unsigned NOT NULL default '0',
  `joinedred` smallint unsigned NOT NULL default '0',
  `joinedblue` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `redwon` smallint unsigned NOT NULL default '0',
  `redlost` smallint unsigned NOT NULL default '0',
  `bluewon` smallint unsigned NOT NULL default '0',
  `bluelost` smallint unsigned NOT NULL default '0',
  `redflagsdefended` smallint unsigned NOT NULL default '0',
  `blueflagsdefended` smallint unsigned NOT NULL default '0',
  `redflagsdropped` smallint unsigned NOT NULL default '0',
  `blueflagsdropped` smallint unsigned NOT NULL default '0',
  `redflagscaptured` smallint unsigned NOT NULL default '0',
  `blueflagscaptured` smallint unsigned NOT NULL default '0',
  `redpointcaptured` smallint unsigned NOT NULL default '0',
  `bluepointcaptured` smallint unsigned NOT NULL default '0',
  `redcaptureblocked` smallint unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `captureblocked` smallint unsigned NOT NULL default '0',
  `pointcaptured` smallint unsigned NOT NULL default '0',
  `redflagspickedup` smallint unsigned NOT NULL default '0',
  `blueflagspickedup` smallint unsigned NOT NULL default '0',
  `dispenserdestroy` smallint unsigned NOT NULL default '0',
  `sentrydestroy` smallint unsigned NOT NULL default '0',
  `teleporterdestroy` smallint unsigned NOT NULL default '0',
  `sapperdestroy` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_source_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `redkills` smallint unsigned NOT NULL default '0',
  `redassists` smallint unsigned NOT NULL default '0',
  `bluekills` smallint unsigned NOT NULL default '0',
  `blueassists` smallint unsigned NOT NULL default '0',
  `reddeaths` smallint unsigned NOT NULL default '0',
  `bluedeaths` smallint unsigned NOT NULL default '0',
  `joinedred` smallint unsigned NOT NULL default '0',
  `joinedblue` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `redwon` smallint unsigned NOT NULL default '0',
  `redlost` smallint unsigned NOT NULL default '0',
  `bluewon` smallint unsigned NOT NULL default '0',
  `bluelost` smallint unsigned NOT NULL default '0',
  `redflagsdefended` smallint unsigned NOT NULL default '0',
  `blueflagsdefended` smallint unsigned NOT NULL default '0',
  `redflagsdropped` smallint unsigned NOT NULL default '0',
  `blueflagsdropped` smallint unsigned NOT NULL default '0',
  `redflagscaptured` smallint unsigned NOT NULL default '0',
  `blueflagscaptured` smallint unsigned NOT NULL default '0',
  `redpointcaptured` smallint unsigned NOT NULL default '0',
  `bluepointcaptured` smallint unsigned NOT NULL default '0',
  `redcaptureblocked` smallint unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint unsigned NOT NULL default '0',
  `redflagspickedup` smallint unsigned NOT NULL default '0',
  `blueflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `captureblocked` smallint unsigned NOT NULL default '0',
  `pointcaptured` smallint unsigned NOT NULL default '0',
  `dispenserdestroy` smallint unsigned NOT NULL default '0',
  `sentrydestroy` smallint unsigned NOT NULL default '0',
  `teleporterdestroy` smallint unsigned NOT NULL default '0',
  `sapperdestroy` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `revenge` smallint unsigned NOT NULL default '0',
  `chargedeployed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_source_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `redkills` smallint unsigned NOT NULL default '0',
  `redassists` smallint unsigned NOT NULL default '0',
  `bluekills` smallint unsigned NOT NULL default '0',
  `blueassists` smallint unsigned NOT NULL default '0',
  `reddeaths` smallint unsigned NOT NULL default '0',
  `bluedeaths` smallint unsigned NOT NULL default '0',
  `joinedred` smallint unsigned NOT NULL default '0',
  `joinedblue` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `redwon` smallint unsigned NOT NULL default '0',
  `redlost` smallint unsigned NOT NULL default '0',
  `bluewon` smallint unsigned NOT NULL default '0',
  `bluelost` smallint unsigned NOT NULL default '0',
  `redflagsdefended` smallint unsigned NOT NULL default '0',
  `blueflagsdefended` smallint unsigned NOT NULL default '0',
  `redflagsdropped` smallint unsigned NOT NULL default '0',
  `blueflagsdropped` smallint unsigned NOT NULL default '0',
  `redflagscaptured` smallint unsigned NOT NULL default '0',
  `blueflagscaptured` smallint unsigned NOT NULL default '0',
  `redpointcaptured` smallint unsigned NOT NULL default '0',
  `bluepointcaptured` smallint unsigned NOT NULL default '0',
  `redcaptureblocked` smallint unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint unsigned NOT NULL default '0',
  `redflagspickedup` smallint unsigned NOT NULL default '0',
  `blueflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `captureblocked` smallint unsigned NOT NULL default '0',
  `pointcaptured` smallint unsigned NOT NULL default '0',
  `dispenserdestroy` smallint unsigned NOT NULL default '0',
  `sentrydestroy` smallint unsigned NOT NULL default '0',
  `teleporterdestroy` smallint unsigned NOT NULL default '0',
  `sapperdestroy` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `revenge` smallint unsigned NOT NULL default '0',
  `chargedeployed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_roles_source_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_role_data_source_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

-- Moved from defaults.sql.
INSERT INTO `ps_config_events` (`id`, `gametype`, `modtype`, `eventname`, `alias`, `regex`, `idx`, `ignore`, `codefile`) 
    VALUES 
        (1,'source','','kill','','/^\"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',10,0,''),
        (2,'source','','attacked','','/^\"(.+(?:<[^>]*>))\" attacked \"(.+(?:<[^>]*>))\" with \"([^\"]+)\"(.*)/',20,1,''),
        (3,'source','','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered \"([^\"]+)\"(.*)/',30,0,''),
        (4,'source','','round','','/^World triggered \"([^\"]+)\"(.*)/',40,0,''),
        (5,'source','','entered_game','','/^\"(.+(?:<[^>]*>))\" entered the game(.*)/',50,0,''),
        (6,'source','','joined_team','','/^\"(.+(?:<[^>]*>))\" joined team \"([^\"]+)\"/',60,0,''),
        (7,'source','','suicide','','/^\"(.+(?:<[^>]*>))\" committed suicide with \"([^\"]+)\"(.*)/',70,0,''),
        (8,'source','','changed_name','','/^\"(.+(?:<[^>]*>))\" changed name to \"([^\"]+)\"/',80,0,''),
        (9,'source','','connected','','/^\"(.+(?:<[^>]*>))\" connected, address \"([^\"]+)\"/',90,0,''),
        (10,'source','','connected_steamid','','/^\"(.+(?:<[^>]*>))\" (?:STEAM|VALVE) USERID (.+)/',100,0,''),
        (11,'source','','disconnected','','/^\"(.+(?:<[^>]*>))\" disconnected/',110,0,''),
        (12,'source','','chat','','/^\"(.+(?:<[^>]*>))\" say(_team)* \"(.*)\"?(.*)/',120,0,''),
        (13,'source','','rcon','','/^(Bad )?Rcon: \"rcon (-*\\d+) \"?(.*?)\"? (.+?)(?:\" from \"([^\"]+)\")?/',130,1,''),
        (14,'source','','cheated','','/^Secure: \"(.+(?:<[^>]*>))\" was detected cheating/',140,0,''),
        (15,'source','','ban','','/^(Addip|Ban(?:id)?): \"([^\"]+)\" was (?:kicked and )?(?:banned)(?: by IP)? \"([^\"]+)\" by \"([^\"]+)\"(.*)/',150,1,''),
        (16,'source','','unban','','/^Remove(id|ip): \"([^\"]+)\" was unbanned by \"(.+(?:<[^>]*>))\"(.*)/',160,1,''),
        (17,'source','','kick','','/^Kick: \"(.+(?:<[^>]*>))\" was kicked by \"(.+(?:<[^>]*>)?)\"(.*)/',170,0,''),
        (18,'source','','pingkick','','/^\"(.+(?:<[^>]*>))\" kicked due to high ping(.*)/',180,0,''),
        (19,'source','','ffkick','','/^\"(.+(?:<[^>]*>))\" has been auto kicked from the game for TKing/',190,0,''),
        (20,'source','','startedmap','','/^(Started|Loading) map \"([^\"]+)\"(.*)/',200,0,''),
        (21,'source','','logstartend','','/^Log file (started|closed)(.*)/',210,0,''),
        (22,'source','','ignored1','','/^[Ss]erver (?:cvars?|say|shutdown)/',220,1,''),
        (23,'source','','ignored2','','/^(?:\\]TSC\\[|Succeeded|FATAL|-|Loaded)/',230,1,''),
        (24,'source','','ignored3','','/^(?:Config|Swear|server_)/',240,1,''),
        (25,'source','','ignored4','','/^\"[^\"]+\" = \"/',250,1,''),
        (27,'source','tf2','teamtrigger','','/^Team \"([^\"]+)\" triggered \"([^\"]+)\"(.*)/',270,0,''),
        (33,'source','','changed_role','','/^\"(.+(?:<[^>]*>))\" changed role to \"([^\"]+)\"/',330,0,''),
        (39,'source','tf2','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered \"([^\"]+)\"(?: against \"(.+(?:<[^>]*>))\")?(.*)/',390,0,''),
        (45,'source','','rcon2','','/^rcon from/',130,1,''),
        (46,'source','tf2','tf2_kick','kick','/^Kick:/',450,1,''),
        (47,'source','tf2','tf2_teamscore','','/^Team \"([^\"]+)\" (\\w+) score \"(\\d+)\" with \"(\\d+)\" players/',470,1,''),
        (48,'source','','spatial','','/^\\[KTRAJ\\] \"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',480,0,''),
        (49,'source','','plugin','','/^\\[[^\\]]+\\]/',490,1,''),
        (50,'source','','console','','/^(CONSOLE|PLAYER FILTER) :/',500,1,''),
        (100,'source','','ignored5','','/^Server name is \"([^"]+)\"/',1000,1,''),
        (101,'source','','ignored6','','/^Connection to Steam servers successful./',1010,1,''),
        (102,'source','','ignored7','','/^VAC secure mode is activated./',1020,1,''),
        (103,'source','','ignored8','','/^Assigned anonymous gameserver Steam ID \[(.:\\d:\\d+:\\d+)\]./',1030,1,''),
        (104,'source','','ignored9','','/^Public IP is ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|(\\d{1,3}\.){3}\\d{1,3}./',1040,1,'');

INSERT INTO `ps_config_plrbonuses` (`id`, `eventname`, `enactor`, `enactor_team`, `victim`, `victim_team`, `description`, `gametype`, `modtype`) 
    VALUES 
        (27,'round_win',0,50,0,-50,'TEAM event that fires when a round ends and a team won','source','tf2'),
        (34,'ffkill',-10,0,0,0,'when a player kills a team mate','',''),
        (36,'kill_assist',0,0,0,0,'When a player assists in another kill','source','tf2'),
        (37,'flag_defended',5,0,0,0,'When a player defends a flag','source','tf2'),
        (38,'flag_captured',5,0,0,0,'When a player captures a flag','source','tf2'),
        (39,'chargedeployed',0,0,0,0,'When a player (medic) deploys their uber charge thingy','source','tf2'),
        (40,'captureblocked',0,0,0,0,'When a player blocks another from capturing a point','source','tf2'),
        (41,'pointcaptured',0,5,0,-5,'TEAM event that fires when a point is captured','source','tf2');

INSERT INTO `ps_config_awards` (`id`, `enabled`, `idx`, `type`, `negative`, `class`, `name`, `groupname`, `phrase`, `expr`, `order`, `where`, `limit`, `format`, `gametype`, `modtype`, `rankedonly`, `description`) 
    VALUES 
        (4,1,10,'player',0,'','Highest Skill','','{$player.link} has the highest skill with {$award.value}','{$skill}','desc','',0,'%.02f',NULL,NULL,1,'Player with the highest skill'),
        (6,1,20,'player',0,'','Most Kills','','{$player.link} has killed the most players ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Player with the most kills (any team)'),
        (8,1,70,'player',0,'','Most Time Online','','{$player.link} has been online the longest ({$award.value})','{$onlinetime}','desc','',25,'compacttime',NULL,NULL,1,'Player with the most online time'),
        (9,1,190,'weaponclass',0,'','Most Kills with {$weapon.class} weapons','','{$player.link} has the most {$weapon.class} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with {$weapon.class} type weapons (including: {$weapon.list}).'),
        (10,1,180,'weapon',0,'','Most Kills with {$weapon.name}','','{$player.link} has the most {$weapon.link} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with a {$weapon.name}'),
        (13,1,30,'player',0,'','Most Bonus Points','','{$player.link} achieved the most bonus points ({$award.value})','{$totalbonus}','desc','',25,'commify',NULL,NULL,1,'Player that has achieved the most bonus points.'),
        (22,1,140,'player',0,'','Most Flags Captured','','{$player.link} has captured the most flags ({$award.value})','{$flagscaptured}','desc','',10,'commify','source','tf2',1,'Player has captured the most flags.'),
        (23,1,50,'player',1,'','Worst Teammate','','{$player.link} has killed the most teammates ({$award.value})','{$ffkills}','desc','',0,'commify',NULL,NULL,1,'Player with the most friendly fire kills (ie: Worst Teammate)'),
        (25,1,60,'player',1,'','Worst Team Kill Percentage','','{$player.link} has the highest team kill percentage ({$award.value})','{$ffkills} / {$kills} * 100','desc','',0,'%0.02f%%',NULL,NULL,1,'Player with the highest team kill percentage.'),
        (27,1,130,'player',0,'','Most Backstabs','','{$player.link} has the most sneaky backstabs ({$award.value})','{$backstabkills}','desc','',0,'commify','source','tf2',1,'Players that are sneaky and like to kill others from the shadows!'),
        (28,1,160,'player',0,'','Most Flags Defended','','{$player.link} has defended the most flags ({$award.value})','{$flagsdefended}','desc','',1,'%s','source','tf2',1,'Player who has defended (or returned) the most flags from the enemy.'),
        (33,1,330,'player',0,'','Most Active Medic','','{$player.link} is the most active medic with {$award.value} medic actions.','{$bandage}','desc','',10,'commify','source','tf2',1,'Player with the most medic actions.'),
        (40,1,400,'player',0,'','Homewrecker','','{$player.link} destroyed the most structures ({$award.value})','{$structuresdestroyed}','desc','',10,'commify','source','tf2',1,'Player that enjoys kicking over sand castles.');
        
INSERT INTO `ps_config_overlays` (`id`, `gametype`, `modtype`, `map`, `minx`, `miny`, `maxx`, `maxy`, `width`, `height`, `flipv`, `fliph`, `rotate`) 
    VALUES 
        (135, 'source', 'tf2', 'cp_badlands', -2504, -4840, 2504, 4840, 861, 903, 1, 0, 0),
        (136, 'source', 'tf2', 'cp_broma', -4460, -1800, 320, 2912, 932, 930, 1, 0, 0),
        (137, 'source', 'tf2', 'cp_broma_b6', -4460, -1800, 320, 2912, 932, 930, 1, 0, 0),
        (138, 'source', 'tf2', 'cp_castle3', -2736, -2640, 8328, 6896, 1304, 1126, 1, 0, 0),
        (139, 'source', 'tf2', 'cp_castle4', -2736, -2650, 8333, 6896, 1088, 940, 1, 0, 0),
        (140, 'source', 'tf2', 'cp_corporation_b1', -2952, -3272, 2980, 2015, 1009, 898, 1, 0, 0),
        (141, 'source', 'tf2', 'cp_corporation_b2', -2952, -3272, 2980, 2015, 881, 786, 1, 0, 0),
        (142, 'source', 'tf2', 'cp_desertfortress', -2794, -2388, 2494, 2892, 886, 884, 1, 0, 0),
        (143, 'source', 'tf2', 'cp_dogblu_b3', -1048, -2392, 3816, 10968, 378, 1049, 1, 0, 0),
        (144, 'source', 'tf2', 'cp_dustbowl', -3716, -2912, 2856, 3422, 928, 915, 1, 0, 0),
        (145, 'source', 'tf2', 'cp_egypt', -7084, -7092, 4092, 9056, 770, 1115, 1, 0, 0),
        (146, 'source', 'tf2', 'cp_fastlane_b1', -1924, -6696, 1924, 5672, 345, 1117, 1, 0, 0),
        (147, 'source', 'tf2', 'cp_four_trees_v2', -1348, -4693, 1874, 4250, 443, 1172, 1, 0, 0),
        (148, 'source', 'tf2', 'cp_granary', -4224, -6868, 1153, 6868, 429, 1140, 1, 0, 0),
        (149, 'source', 'tf2', 'cp_gravelpit', -5376, -1024, 2248, 5636, 848, 741, 1, 0, 0),
        (150, 'source', 'tf2', 'cp_jailbreak_b3', -4200, -9615, 495, -1168, 625, 1119, 1, 0, 0),
        (151, 'source', 'tf2', 'cp_japan_v2', 3092, -3617, 11784, -1140, 1598, 430, 1, 0, 0),
        (152, 'source', 'tf2', 'cp_junction_v2', -3329, -1018, 2528, 5080, 831, 898, 1, 0, 0),
        (153, 'source', 'tf2', 'cp_labor', -1602, -4862, 1444, 3096, 453, 1175, 1, 0, 0),
        (154, 'source', 'tf2', 'cp_lazytown', -3560, -2856, 1768, 6696, 629, 1125, 1, 0, 0),
        (155, 'source', 'tf2', 'cp_redstone_b1', -2026, -7008, 2977, 6340, 429, 1118, 1, 0, 0),
        (156, 'source', 'tf2', 'cp_redstone_b2', -2026, -7008, 2977, 6340, 429, 1118, 1, 0, 0),
        (157, 'source', 'tf2', 'cp_roswell', -840, -1695, 3391, 4121, 720, 987, 1, 0, 0),
        (158, 'source', 'tf2', 'cp_roswell_b2', -840, -1695, 3391, 4121, 720, 987, 1, 0, 0),
        (159, 'source', 'tf2', 'cp_silo_b3', -872, -4120, 2016, 6360, 240, 1124, 1, 0, 0),
        (160, 'source', 'tf2', 'cp_spywinder_optim', -3308, -4461, 1287, 134, 780, 780, 1, 0, 0),
        (161, 'source', 'tf2', 'cp_steel_b4', -3286, -4128, 4193, 2706, 1097, 992, 1, 0, 0),
        (162, 'source', 'tf2', 'cp_switchback_b5', -1624, -3488, 2000, 9104, 328, 1135, 1, 0, 0),
        (163, 'source', 'tf2', 'cp_vertigo_beta3', -1208, -2766, 2792, 2860, 804, 1102, 1, 0, 0),
        (164, 'source', 'tf2', 'cp_warpath2_1b', -3761, -2962, 3983, 2962, 1200, 915, 1, 0, 0),
        (165, 'source', 'tf2', 'cp_well', -4608, -6696, 1534, 7464, 480, 1109, 1, 0, 0),
        (166, 'source', 'tf2', 'ctf_2fort', -1960, -4248, 1960, 4248, 396, 907, 1, 0, 0),
        (167, 'source', 'tf2', 'ctf_chaos', -1656, -660, 1656, 3108, 657, 746, 1, 0, 0),
        (168, 'source', 'tf2', 'ctf_impact2', -768, -3128, 2454, 3968, 427, 934, 1, 0, 0),
        (169, 'source', 'tf2', 'ctf_mach4', -969, -2129, 1672, 3620, 515, 1113, 1, 0, 0),
        (170, 'source', 'tf2', 'ctf_quarry', -1350, -9, 1610, 6411, 456, 942, 1, 0, 0),
        (171, 'source', 'tf2', 'ctf_turbine_v3', -3856, -1752, 3856, 1752, 1506, 684, 1, 0, 0),
        (172, 'source', 'tf2', 'ctf_well', -4608, -5800, 1534, 6568, 500, 1017, 1, 0, 0),
        (173, 'source', 'tf2', 'pl_goldrush', -9215, -4093, -1539, 4111, 901, 944, 1, 0, 0);
        
INSERT INTO `ps_config` (`id`, `conftype`, `section`, `var`, `value`, `label`, `type`, `locked`, `verifycodes`, `options`, `help`) 
    VALUES 
        (1,'main',NULL,'meta_keywords','PsychoStats Game Server Player Statistics Team Fortress 2 TF TF2 Valve','Site HTML Meta Key Words','text',0,'','','These are the HTML meta key words for your PsychoStats.  They are used by search engines to provide search results.');
